/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PJ Banking API
 * OpenAPI specification describing the PJ banking endpoints exposed by the
Finance CoPilot backend. These routes power bank account discovery,
transaction browsing and financial summaries for PJ clients.

 * OpenAPI spec version: 1.0.0
 */
import type { BankTransactionCategorizedAs } from "./bankTransactionCategorizedAs";
import type { BankTransactionLinkedLegsItem } from "./bankTransactionLinkedLegsItem";

export interface BankTransaction {
  /**
   * Identifier provided by the originating bank, when available
   * @nullable
   */
  accountId?: string | null;
  /** Positive values are inflows, negative values are outflows */
  amount: number;
  /** Identifier of the bank account that owns the transaction */
  bankAccountId: string;
  /** Unique identifier assigned to the transaction inside Finance CoPilot */
  bankTxId: string;
  /** @nullable */
  categorizedAs?: BankTransactionCategorizedAs;
  /**
   * Categorization source (manual, rule, auto)
   * @nullable
   */
  categorizedBy?: string | null;
  /**
   * Identifier of the rule used for categorization when applicable
   * @nullable
   */
  categorizedRuleId?: string | null;
  /** Transaction posting date in DD/MM/YYYY format */
  date: string;
  /** Raw description obtained from the bank statement */
  desc: string;
  /**
   * Legacy DFC category associated with the transaction
   * @nullable
   */
  dfcCategory?: string | null;
  /**
   * Legacy DFC item associated with the transaction
   * @nullable
   */
  dfcItem?: string | null;
  /**
   * Unique identifier provided by the OFX file
   * @nullable
   */
  fitid?: string | null;
  /** Sale legs that were reconciled against this transaction */
  linkedLegs: BankTransactionLinkedLegsItem[];
  /** Indicates whether the transaction is reconciled with a sale */
  reconciled: boolean;
  /**
   * SHA256 hash of the imported OFX file used for deduplication
   * @nullable
   */
  sourceHash?: string | null;
}
