/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PJ Banking API
 * OpenAPI specification describing the PJ banking endpoints exposed by the
Finance CoPilot backend. These routes power bank account discovery,
transaction browsing and financial summaries for PJ clients.

 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type BankTransactionCategorizedAs = {
  /** Indicates whether the categorization was automatic */
  auto?: boolean;
  /** @nullable */
  group?: string | null;
  /** @nullable */
  subcategory?: string | null;
  /** @nullable */
  categoryId?: string | null;
  /** @nullable */
  categoryPath?: string | null;
} | null;
