/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PJ Banking API
 * OpenAPI specification describing the PJ banking endpoints exposed by the
Finance CoPilot backend. These routes power bank account discovery,
transaction browsing and financial summaries for PJ clients.

 * OpenAPI spec version: 1.0.0
 */

export interface BankAccountSummary {
  /** Masked bank account number where only the last digits are visible */
  accountNumberMask: string;
  /** Type of the bank account (e.g. corrente, poupanca) */
  accountType: string;
  /** Display name of the bank */
  bankName: string;
  /** ISO currency code (e.g. BRL) */
  currency: string;
  /** Bank account identifier */
  id: string;
  /** Indicates whether the account is active and available for ingestion */
  isActive: boolean;
}
