/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PJ Banking API
 * OpenAPI specification describing the PJ banking endpoints exposed by the
Finance CoPilot backend. These routes power bank account discovery,
transaction browsing and financial summaries for PJ clients.

 * OpenAPI spec version: 1.0.0
 */

export interface DailyNetFlow {
  /** Day of the aggregated cash flow in DD/MM/YYYY format */
  date: string;
  /** Net cash flow for the day (positive for inflow, negative for outflow) */
  net: number;
}
