/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PJ Banking API
 * OpenAPI specification describing the PJ banking endpoints exposed by the
Finance CoPilot backend. These routes power bank account discovery,
transaction browsing and financial summaries for PJ clients.

 * OpenAPI spec version: 1.0.0
 */

export interface Pagination {
  hasNextPage: boolean;
  hasPreviousPage: boolean;
  /** @minimum 1 */
  limit: number;
  /** @minimum 1 */
  page: number;
  /** @minimum 0 */
  totalItems: number;
  /** @minimum 0 */
  totalPages: number;
}
