/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PJ Banking API
 * OpenAPI specification describing the PJ banking endpoints exposed by the
Finance CoPilot backend. These routes power bank account discovery,
transaction browsing and financial summaries for PJ clients.

 * OpenAPI spec version: 1.0.0
 */
import type { PjCategoryTreeNodeType } from './pjCategoryTreeNodeType';

export interface PjCategoryTreeNode {
  acceptsPostings: boolean;
  /** @nullable */
  baseCategoryId?: string | null;
  children: PjCategoryTreeNode[];
  /** @nullable */
  code?: string | null;
  /** @nullable */
  description?: string | null;
  id: string;
  /** @nullable */
  isCore?: boolean | null;
  level: number;
  name: string;
  /** @nullable */
  parentId: string | null;
  path: string;
  sortOrder: number;
  type: PjCategoryTreeNodeType;
}
