/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PJ Banking API
 * OpenAPI specification describing the PJ banking endpoints exposed by the
Finance CoPilot backend. These routes power bank account discovery,
transaction browsing and financial summaries for PJ clients.

 * OpenAPI spec version: 1.0.0
 */

export type PjClientCategoryNodeAllOfType = typeof PjClientCategoryNodeAllOfType[keyof typeof PjClientCategoryNodeAllOfType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PjClientCategoryNodeAllOfType = {
  client: 'client',
} as const;
