/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PJ Banking API
 * OpenAPI specification describing the PJ banking endpoints exposed by the
Finance CoPilot backend. These routes power bank account discovery,
transaction browsing and financial summaries for PJ clients.

 * OpenAPI spec version: 1.0.0
 */

export type SummaryResponseKpis = {
  averageDailyNetFlow: number;
  averageTicketIn: number;
  averageTicketOut: number;
  cashConversionRatio: number;
  inflowCount: number;
  largestIn: number;
  largestOut: number;
  outflowCount: number;
  overdueReceivableAmount: number;
  overdueReceivableCount: number;
  projectedBalance: number;
  receivableAmount: number;
  receivableCount: number;
};
