/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PJ Banking API
 * OpenAPI specification describing the PJ banking endpoints exposed by the
Finance CoPilot backend. These routes power bank account discovery,
transaction browsing and financial summaries for PJ clients.

 * OpenAPI spec version: 1.0.0
 */
import type { SummaryResponseKpis } from './summaryResponseKpis';
import type { SummaryResponseMetadata } from './summaryResponseMetadata';
import type { SummaryResponseSeries } from './summaryResponseSeries';
import type { SummaryResponseTotals } from './summaryResponseTotals';

export interface SummaryResponse {
  bankAccountId: string;
  clientId: string;
  /**
   * Start of the effective analysis window in DD/MM/YYYY format
   * @nullable
   */
  from?: string | null;
  kpis: SummaryResponseKpis;
  metadata: SummaryResponseMetadata;
  series: SummaryResponseSeries;
  /**
   * End of the effective analysis window in DD/MM/YYYY format
   * @nullable
   */
  to?: string | null;
  totals: SummaryResponseTotals;
}
