/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PJ Banking API
 * OpenAPI specification describing the PJ banking endpoints exposed by the
Finance CoPilot backend. These routes power bank account discovery,
transaction browsing and financial summaries for PJ clients.

 * OpenAPI spec version: 1.0.0
 */
import type {
  AccountsResponse,
  BankTransactionListResponse,
  GetApiPjSummaryParams,
  GetApiPjTransactionsParams,
  SummaryResponse,
} from "./model";
import { sdkClient } from "./httpClient";

export const getPJBankingAPI = () => {
  /**
 * Returns the bank accounts that are available to the authenticated PJ
client. Only a subset of bank account fields is exposed to avoid
leaking sensitive identifiers.

 * @summary List bank accounts available for the authenticated PJ client
 */
  const getApiPjAccounts = () => {
    return sdkClient<AccountsResponse>({
      url: `/api/pj/accounts`,
      method: "GET",
    });
  };

  /**
 * Returns the paginated bank transactions imported for a specific PJ
bank account. Transactions are filtered by the optional period and
sorted by posting date.

 * @summary List paginated bank transactions for a PJ client account
 */
  const getApiPjTransactions = (params: GetApiPjTransactionsParams) => {
    return sdkClient<BankTransactionListResponse>({
      url: `/api/pj/transactions`,
      method: "GET",
      params,
    });
  };

  /**
 * Calculates aggregated totals, KPIs and daily net flow series for a PJ
bank account inside the requested date range. When the date range is
omitted the backend automatically expands it to the available
transaction history.

 * @summary Retrieve aggregated cash-flow summary for a PJ client account
 */
  const getApiPjSummary = (params: GetApiPjSummaryParams) => {
    return sdkClient<SummaryResponse>({
      url: `/api/pj/summary`,
      method: "GET",
      params,
    });
  };

  return { getApiPjAccounts, getApiPjTransactions, getApiPjSummary };
};
export type GetApiPjAccountsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPJBankingAPI>["getApiPjAccounts"]>>
>;
export type GetApiPjTransactionsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPJBankingAPI>["getApiPjTransactions"]>
  >
>;
export type GetApiPjSummaryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPJBankingAPI>["getApiPjSummary"]>>
>;
