/* tslint:disable */
/* eslint-disable */
/**
 * PJ Banking API
 * OpenAPI specification describing the PJ banking endpoints exposed by the Finance CoPilot backend. These routes power bank account discovery, transaction browsing and financial summaries for PJ clients. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: engineering@financecopilot.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface BankAccountSummary {
    /**
     * Bank account identifier
     */
    'id': string;
    /**
     * Display name of the bank
     */
    'bankName': string;
    /**
     * Masked bank account number where only the last digits are visible
     */
    'accountNumberMask': string;
    /**
     * Type of the bank account (e.g. corrente, poupanca)
     */
    'accountType': string;
    /**
     * ISO currency code (e.g. BRL)
     */
    'currency': string;
    /**
     * Indicates whether the account is active and available for ingestion
     */
    'isActive': boolean;
}

