/* tslint:disable */
/* eslint-disable */
/**
 * PJ Banking API
 * OpenAPI specification describing the PJ banking endpoints exposed by the Finance CoPilot backend. These routes power bank account discovery, transaction browsing and financial summaries for PJ clients. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: engineering@financecopilot.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BankTransactionCategorizedAs } from './bank-transaction-categorized-as';
// May contain unused imports in some cases
// @ts-ignore
import type { BankTransactionLinkedLegsInner } from './bank-transaction-linked-legs-inner';

export interface BankTransaction {
    /**
     * Unique identifier assigned to the transaction inside Finance CoPilot
     */
    'bankTxId': string;
    /**
     * Transaction posting date in DD/MM/YYYY format
     */
    'date': string;
    /**
     * Raw description obtained from the bank statement
     */
    'desc': string;
    /**
     * Positive values are inflows, negative values are outflows
     */
    'amount': number;
    /**
     * Identifier of the bank account that owns the transaction
     */
    'bankAccountId': string;
    /**
     * Identifier provided by the originating bank, when available
     */
    'accountId'?: string;
    /**
     * Unique identifier provided by the OFX file
     */
    'fitid'?: string;
    /**
     * SHA256 hash of the imported OFX file used for deduplication
     */
    'sourceHash'?: string;
    /**
     * Sale legs that were reconciled against this transaction
     */
    'linkedLegs': Array<BankTransactionLinkedLegsInner>;
    /**
     * Indicates whether the transaction is reconciled with a sale
     */
    'reconciled': boolean;
    'categorizedAs'?: BankTransactionCategorizedAs;
    /**
     * Legacy DFC category associated with the transaction
     */
    'dfcCategory'?: string;
    /**
     * Legacy DFC item associated with the transaction
     */
    'dfcItem'?: string;
    /**
     * Categorization source (manual, rule, auto)
     */
    'categorizedBy'?: string;
    /**
     * Identifier of the rule used for categorization when applicable
     */
    'categorizedRuleId'?: string;
}

