/* tslint:disable */
/* eslint-disable */
/**
 * PJ Banking API
 * OpenAPI specification describing the PJ banking endpoints exposed by the Finance CoPilot backend. These routes power bank account discovery, transaction browsing and financial summaries for PJ clients. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: engineering@financecopilot.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DailyNetFlow {
    /**
     * Day of the aggregated cash flow in DD/MM/YYYY format
     */
    'date': string;
    /**
     * Net cash flow for the day (positive for inflow, negative for outflow)
     */
    'net': number;
}

