/* tslint:disable */
/* eslint-disable */
/**
 * PJ Banking API
 * OpenAPI specification describing the PJ banking endpoints exposed by the Finance CoPilot backend. These routes power bank account discovery, transaction browsing and financial summaries for PJ clients. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: engineering@financecopilot.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SummaryResponseKpis } from './summary-response-kpis';
// May contain unused imports in some cases
// @ts-ignore
import type { SummaryResponseMetadata } from './summary-response-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { SummaryResponseSeries } from './summary-response-series';
// May contain unused imports in some cases
// @ts-ignore
import type { SummaryResponseTotals } from './summary-response-totals';

export interface SummaryResponse {
    'clientId': string;
    'bankAccountId': string;
    /**
     * Start of the effective analysis window in DD/MM/YYYY format
     */
    'from'?: string;
    /**
     * End of the effective analysis window in DD/MM/YYYY format
     */
    'to'?: string;
    'totals': SummaryResponseTotals;
    'kpis': SummaryResponseKpis;
    'series': SummaryResponseSeries;
    'metadata': SummaryResponseMetadata;
}

