/* tslint:disable */
/* eslint-disable */
/**
 * PJ Banking API
 * OpenAPI specification describing the PJ banking endpoints exposed by the Finance CoPilot backend. These routes power bank account discovery, transaction browsing and financial summaries for PJ clients. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: engineering@financecopilot.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SummaryResponseKpis {
    'inflowCount': number;
    'outflowCount': number;
    'averageTicketIn': number;
    'averageTicketOut': number;
    'largestIn': number;
    'largestOut': number;
    'averageDailyNetFlow': number;
    'cashConversionRatio': number;
    'receivableAmount': number;
    'receivableCount': number;
    'overdueReceivableAmount': number;
    'overdueReceivableCount': number;
    'projectedBalance': number;
}

